# Generated by Django 5.1.1 on 2024-09-21 03:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigments_tasked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 9, 21)),
        ),
    ]
