# Generated by Django 5.1.1 on 2024-09-21 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_assigment_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
