# Generated by Django 5.1.1 on 2024-09-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_assigment_milestone_assigments_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='assigments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='project.assigment'),
        ),
    ]
