# Generated by Django 5.1.1 on 2024-09-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_milestone_assigments_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='milestone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigments', to='project.milestone'),
            preserve_default=False,
        ),
    ]
