# Generated by Django 5.1.1 on 2024-09-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_assigment_milestone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='responsible',
        ),
    ]
