# Generated by Django 5.1.1 on 2024-09-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_user_task_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
        ),
    ]
