# Generated by Django 5.1.1 on 2024-09-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_timelinechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigment',
            old_name='priority',
            new_name='state',
        ),
    ]
