# Generated by Django 5.1.1 on 2024-09-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='work_experiences',
        ),
    ]
