# Generated by Django 5.1.1 on 2024-09-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_remove_freelancerprofile_work_experiences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='profile.portfolio'),
        ),
    ]
