# Generated by Django 5.1.1 on 2024-09-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_portfolioproject_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expedition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
