# Generated by Django 5.1.1 on 2024-09-20 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_course_expedition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experience_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
