# Generated by Django 5.1.1 on 2024-09-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_remove_freelancerprofile_califications_rating_and_more'),
        ('profile', '0006_workexperience_image'),
    ]

    operations = [
    ]
