# Generated by Django 5.1.1 on 2024-09-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_workexperience_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='image',
        ),
    ]
