# Generated by Django 5.1.1 on 2024-09-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
