# Generated by Django 5.1.1 on 2024-09-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0008_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
