# Generated by Django 5.1.1 on 2024-09-16 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_controller', '0010_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
