# Generated by Django 5.1.1 on 2024-09-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_profile_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='califications',
            field=models.ManyToManyField(blank=True, related_name='freelancer_califications', to='freelancer_profile_creation.calificacion'),
        ),
    ]
