# Generated by Django 5.1.1 on 2024-09-12 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_profile_creation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectoportafolio',
            name='perfil',
        ),
        migrations.RenameField(
            model_name='curriculumvitae',
            old_name='perfil',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='archivo',
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('course_link', models.URLField(blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('activities_done', models.TextField()),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='ProyectoPortafolio',
        ),
    ]
