# Generated by Django 5.1.1 on 2024-09-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_profile_creation', '0004_freelancerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='freelancer_profile_creation.skill'),
        ),
    ]
